### ISSUE TITLE
accessing classes based on LightTypeTags

### ISSUE THREAD

**Issue by pjfanning** [zio/izumi-reflect#116]
I'm looking at replacing the use of Manifests because Scala3 doesn't support them. I tried out LightTypeTags but could only find string representations of the class for the type and the type args. It's quite possible that I missed the API that supports this because I see class support in the code base.

I used this code in a test and the LightTypeTag repr and typeArgs look good but my use case requires that I be able to get at the classes.
```
  private def fromRuntime[T: ru.TypeTag]: LightTypeTag =
    LightTypeTagImpl.makeLightTypeTag(ru)(ru.typeOf[T])
```

**Comment by neko-kai** [comment]
@pjfanning
You can get the class from `Tag[T].closestClass` e.g. 

```scala
val strTag = implicitly[Tag[String]]
strTag.closestClass
```

**Comment by gaeljw** [comment]
Hi,

I'm having pretty much the same requirement: moving away from `TypeTag`s as Scala 3 doesn't have them anymore, and found this library that could be helpful but stuck with how to get a `Class` from a `LightTypeTag` (or maybe a `Tag` ?).

@neko-kai your example with String gives me a `Class[Object]` rather than a `Class[String]`, is this expected? :thinking:

**Comment by neko-kai** [comment]
@gaeljw Huh, no, it's class[String] in Scala 2 - https://scastie.scala-lang.org/XwHHTuZ3Tb6hH01Zyg0jXw ; but indeed it's Object in Scala 3 - https://scastie.scala-lang.org/DpMffdqUR2CBDF47VvqRcw.

I guess this line is responsible – https://github.com/zio/izumi-reflect/blob/develop/izumi-reflect/izumi-reflect/src/main/scala_3/izumi/reflect/Tags.scala#L131 – I wonder if changing `classOf[Any]` to `classOf[T]` will Just Work on current Scala 3.

**Comment by pjfanning** [comment]
@gaeljw if you just need the class, ClassTags might work - they still seem to work in Scala 3. ClassTags have less information than Manifests (no longer supported in Scala3). At some stage, I will probably try out izumi-reflect but haven't had time to do a full implementation based on izumi-reflect yet.

https://github.com/FasterXML/jackson-module-scala/blob/master/src/main/scala/com/fasterxml/jackson/module/scala/ClassTagExtensions.scala#L228

**Comment by gaeljw** [comment]
@pjfanning unfortunately I need the type parameters, this was the only reason to use `TypeTag` over `ClassTag` in my case. 
FYI, I thought I could get them using Scala3 macros but stuck with a similar problem: I've got a String representation that I'm not able to convert to a `Class` instance reliably. (https://github.com/lampepfl/dotty/issues/10933)

**Comment by neko-kai** [comment]
Basically, for izumi-reflect, the outer `Tag` contains the closest approximate class, but LightTypeTags themselves do not contain classes inside their tree, meaning that when you have a `Tag[X[A, B]]` instance, you can find the class of `X`, but not classes of `A` & `B`. So for now, a use case of getting the classes for parameters is not covered.

@gaeljw 
> I've got a String representation that I'm not able to convert to a Class instance reliably.

Instead of using the string representation of quoted types to splice a `Class.forName` to later use the string to get the class, maybe you could just directly splice the code that produces the `Class[_]` instance such as `classOf[$t]` or `implicitly[ClassTag[$t]].runtimeClass`? e.g. in pseudocode (I'm not up to date with latest API)

```scala
val typeParams = (tpe: quoted.Type).typeParams
val listOfClassExprs: List[quoted.Expr[Class[_]]] = typeParams.map(t => '{ classOf[$t] })
val expr: quoted.Expr[List[Class[_]] = ???(listOfClassExprs)
```

**Comment by gaeljw** [comment]
@neko-kai Indeed, sound like a good idea. I'll try this and let you know! Thanks :)

**Comment by gaeljw** [comment]
For anyone interested, I've solved my initial use case using a macro that gives me a `ClassTag[_]` rather than a `Class[_]`.
You can see the code on the following project: https://github.com/gaeljw/typetrees/blob/main/src/main/scala/io/github/gaeljw/typetrees/TypeTreeTagMacros.scala#L8
