### ISSUE TITLE
Is izumi-reflect supposed to run on Java 8?

### ISSUE THREAD

**Issue by sideeffffect** [zio/izumi-reflect#196]
When I try to CI my project when running on Java 8, Missinglink gives me the following error:
```
[info] 1 conflicts found! 
[error] Category: Method being called not found
[error]   In artifact: izumi-reflect-thirdparty-boopickle-shaded_2.13-1.1.2.jar
[error]     In class: izumi.reflect.thirdparty.internal.boopickle.EncoderSize
[error]       In method:  writeByteBuffer(java.nio.ByteBuffer):501
[error]       Call to: java.nio.ByteBuffer.mark()
[error]       Problem: Method not found: java.nio.ByteBuffer.mark()
[error]       Found in: rt.jar
[error]       --------
[error] There were 1 conflicts
[error] (server / Compile / missinglinkCheck) There were 1 conflicts
```
https://github.com/Idealiste-cz/ideal-voting-backend/pull/101/checks?check_run_id=3097704499#step:6:43

Is izumi-reflect supposed to run on Java 8 in the first place? I can't see Java 8 be a part of izumi-reflect's CI anywhere.

**Comment by sideeffffect** [comment]
@neko-kai sorry to be a bother, but is this an error that I should pay attention to, or is it actually not an error and I can safely ignore it?

**Comment by neko-kai** [comment]
@sideeffffect Unless the message is a false positive, it's an error; I'll address this is in a few hours.

**Comment by neko-kai** [comment]
@sideeffffect Actually the message was a false positive, but only because the method in question was never used. I just deleted all parts of boopickle that weren't directly used, so this fix should also decrease jar size.

I've just released https://github.com/zio/izumi-reflect/releases/tag/v1.1.3-RC2 which you may update to in lieu of adding an exception in your build, IFF you want to.

>Is izumi-reflect supposed to run on Java 8 in the first place? I can't see Java 8 be a part of izumi-reflect's CI anywhere.

It's supposed to, we don't use Java 8 on CI, but the built artifacts are indirectly tested downstream in ZIO's CI, so I was surprised this wasn't caught...

**Comment by sideeffffect** [comment]
> deleted all parts of boopickle that weren't directly used, so this fix should also decrease jar size

Nice! Thanks Kai :+1: 

> ZIO's CI, so I was surprised this wasn't caught

ZIO doesn't run Missinglink analysis. ZIO doesn't have many dependencies, so it's probably not worth it. Otherwise, any Scala (or even Java) application should employ Missinglink to eliminate preventable runtime failures :wink:
