### ISSUE TITLE
Tag#equals regression since 1.0.0-M8

### ISSUE THREAD

**Issue by nktpro** [zio/izumi-reflect#98]
Since upgrading to ZIO `1.0.3`, which depends on izumi-reflect `1.0.0-M9`, we've been hitting [`Defect in zio.Has: Could not find ${tag} inside ${self}` exceptions](https://github.com/zio/zio/blob/36905905f44a6e47e7921616e464e0e93ac70afb/core/shared/src/main/scala/zio/Has.scala#L181). We managed to narrow the root cause down to a regression of Tag#equals, which seemed to be introduced since `1.0.0-M8` release.

Here's a bare-minimal reproducer:

```scala
package bug

import izumi.reflect.Tag

object SomeService {
  trait Service[T] {}

  final case class Foo()

  val tag1 = Tag[Service[Foo]]
}

object IzumiReflectTagEqualRegression {
  import SomeService._

  def main(args: Array[String]): Unit = {
    val tag2 = Tag[Service[Foo]]

    assert(tag1.tag == tag2.tag)
  }
}
```

The assertion would only succeed in <=`1.0.0-M7` releases.

It's also worth noting that with `-Dizumi.reflect.rtti.optimized.equals=false` system prop, this would work correctly.

**Comment by neko-kai** [comment]
@nktpro 
There's a spurious difference in `.refString` of these two tags - some additional bytes at the end in `tag2` that do not seem to impact the result  - even though they are equivalent and have the same hashCode. May be a bug in serialization code, in `makeParsedLightTypeTagImpl`

<img width="866" alt="Screenshot 2020-11-18 at 10 26 44" src="https://user-images.githubusercontent.com/450507/99518709-df163e00-2988-11eb-8c21-00f1e3fd4a4a.png">

**Comment by neko-kai** [comment]
@nktpro
I think I won't have the time to debug this for a couple of weeks, if you or another contributor are interested in digging into this, `makeParsedLightTypeTagImpl` and/or `LightTypeTagRef`'s boopickle codecs will be the best place to start debugging as per above. There's something corrupting the output string and it may be caused by boopickle's ByteBuffer reuse logic.

**Comment by neko-kai** [comment]
This had nothing to do with ByteBuffer reuse, I was simply not aware that boopickle did output deduplication based on object _references_ for case classes, which would naturally cause unstable output for equal but not the same values. This is disabled now, only Strings are deduplicated, this should have minimal impact on length of Tags since they seldomly shared object references within the graph and most of the data is Strings already.
